force-app/main/default/objects/Account/fields/Is_Person_Account_Created__c.field-meta.xml
<CustomField>
    <fullName>Is_Person_Account_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Person Account Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mailing_Address__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Address__c</fullName>
    <label>Mailing Address</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Account/fields/Person_Email__c.field-meta.xml
<CustomField>
    <fullName>Person_Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Person_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Person_First_Name__c</fullName>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Person_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Person_Last_Name__c</fullName>
    <label>Last Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Person_Phone__c.field-meta.xml
<CustomField>
    <fullName>Person_Phone__c</fullName>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Indicates if the individual is the primary contact for their organization.</description>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Primary Contacts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

force-app/main/default/classes/CreatePersonAccountFromOrgAccount.cls
public class CreatePersonAccountFromOrgAccount {
    public static void createPersonAccount(List<Account> newAccounts) {
        // Get the Record Type Id for Person Accounts
        Id personAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
        
        List<Account> personAccountsToCreate = new List<Account>();
        
        for (Account acc : newAccounts) {
            // Debug the source values
            System.debug('Source Account - Person_Last_Name__c: ' + acc.Person_Last_Name__c);
            System.debug('Source Account - Person_Email__c: ' + acc.Person_Email__c);
            System.debug('Source Account - Mailing_Address__c: ' + acc.Mailing_Address__c);
            
            // Create a new Person Account sObject
            Account personAccount = new Account();
            
            // Map fields from the triggering Account to the new Person Account
            personAccount.RecordTypeId = personAccountRecordTypeId;
            personAccount.FirstName = acc.Person_First_Name__c;
            personAccount.LastName = acc.Person_Last_Name__c;
            personAccount.PersonEmail = acc.Person_Email__c;
            personAccount.Phone = acc.Person_Phone__c;
            personAccount.PersonMobilePhone = acc.Person_Mobile__c;
            
            // Debug the mapped values
            System.debug('Person Account - FirstName: ' + personAccount.FirstName);
            System.debug('Person Account - LastName: ' + personAccount.LastName);
            System.debug('Person Account - PersonEmail: ' + personAccount.PersonEmail);
            
            // Handle the composite mailing address field with proper null checking
            if (acc.Mailing_Address__c != null) {
                try {
                    personAccount.PersonMailingStreet = acc.Mailing_Address__c.getStreet();
                    personAccount.PersonMailingCity = acc.Mailing_Address__c.getCity();
                    personAccount.PersonMailingState = acc.Mailing_Address__c.getState();
                    personAccount.PersonMailingPostalCode = acc.Mailing_Address__c.getPostalCode();
                    personAccount.PersonMailingCountry = acc.Mailing_Address__c.getCountry();
                    
                    System.debug('Address parsed successfully');
                } catch (Exception e) {
                    System.debug('Error parsing address: ' + e.getMessage());
                }
            } else {
                System.debug('Mailing address is null');
            }
            
            personAccountsToCreate.add(personAccount);
        }
        
        // Insert the new Person Accounts in bulk
        if (!personAccountsToCreate.isEmpty()) {
            try {
                insert personAccountsToCreate;
                
                // Rest of your code for updating the original accounts...
                List<Account> accountsToUpdate = new List<Account>();
                for (Integer i = 0; i < personAccountsToCreate.size(); i++) {
                    Account triggeringAccount = newAccounts[i];
                    Account newPersonAccount = personAccountsToCreate[i];
                    
                    triggeringAccount.Primary_Contact__c = newPersonAccount.PersonContactId;
                    triggeringAccount.Is_Person_Account_Created__c = true;
                    accountsToUpdate.add(triggeringAccount);
                }
                
                if (!accountsToUpdate.isEmpty()) {
                    update accountsToUpdate;
                }
            } catch (DmlException e) {
                System.debug('DML Exception: ' + e.getMessage());
                System.debug('First error: ' + e.getDmlMessage(0));
                throw e;
            }
        }
    }
}