force-app/main/default/objects/Invoice__c/fields/Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bill For Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
            <value>
                <fullName>Paid by CP</fullName>
            </value>
            <value>
                <fullName>Payment pending by CP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OldInvoicePDFBatchTest.cls
@isTest
public class OldInvoicePDFBatchTest {

    @testSetup
    static void setupData() {

        // Create Account
        Account acc = new Account(
            Name = 'Test Account'
        );
        insert acc;
 // Create Invoice (Paid)
        Invoice__c inv = new Invoice__c(
            Status__c = 'Paid',
            Bill_To_Account__c = acc.Id
        );
        insert inv;
    }

  
        // Fetch Invoice
        Invoice__c inv = [
            SELECT Id, Name
            FROM Invoice__c
            LIMIT 1
        ];
}